name: Windows Build

on:
  workflow_call:
    inputs:
      ring-version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
        - arch: Win32
          arch_name: i386
        - arch: x64
          arch_name: amd64
        - arch: ARM64
          arch_name: arm64

    steps:
    - name: Checkout ring-markdown
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clone Ring Source
      uses: actions/checkout@v4
      with:
        repository: ringpackages/ringsrc
        path: ring
        ref: ${{ inputs.ring-version }}

    - name: Configure and Build Ring Language for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        cd ring/language
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel
        cmake --install .

    - name: Set RING environment variable
      run: echo "RING=$(pwd)\ring" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Configure and Build ring-markdown lib for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        rmdir /s /q lib
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ring-markdown-windows-${{ matrix.arch_name }}
        path: lib
